con = connect_to_database()
con = run_simulations(                                                                                                                                                                                                                                                         
   ReactiveAgentsDriver.town_parameters("small"),                                                                                                                                                                                                                                             
   ReactiveAgentsDriver.network_parameters(30),                                                                                                                                                                                                                                               
   10,                                                                                                                                                                                                                                                                                   
   ReactiveAgentsDriver.behavior_parameters("Watts", "Random", 5, 5),                                                                                                                                                                                                                          
   1,                                                                                                                                                                                                                                                                                   
   100,                                                                                                                                                                                                                                                                                  
   con,                                                                                                                                                                                                                                                                                 
   STORE_NETWORK_SCM=true,                                                                                                                                                                                                                                                              
   STORE_EPIDEMIC_SCM=true                                                                                                                                                                                                                                                              
   )

# con = run_simulations(                                                                                                                                                                                                                                                         
#    1,                                                                                                                                                                                                                                             
#    ReactiveAgentsDriver.network_parameters(30),                                                                                                                                                                                                                                               
#    10,                                                                                                                                                                                                                                                                                   
#    ReactiveAgentsDriver.behavior_parameters("Random", "Random", 5, 5),                                                                                                                                                                                                                          
#    1,                                                                                                                                                                                                                                                                                   
#    100,                                                                                                                                                                                                                                                                                  
#    con,                                                                                                                                                                                                                                                                                 
#    STORE_NETWORK_SCM=true,                                                                                                                                                                                                                                                              
#    STORE_EPIDEMIC_SCM=true                                                                                                                                                                                                                                                             
#    )

# con = run_simulations(                                                                                                                                                                                                                                                         
#    1,                                                                                                                                                                                                                                             
#    ReactiveAgentsDriver.network_parameters(30),                                                                                                                                                                                                                                               
#    10,                                                                                                                                                                                                                                                                                   
#    ReactiveAgentsDriver.behavior_parameters("Random", "Watts", 5, 5),                                                                                                                                                                                                                          
#    1,                                                                                                                                                                                                                                                                                   
#    100,                                                                                                                                                                                                                                                                                  
#    con,                                                                                                                                                                                                                                                                                 
#    STORE_NETWORK_SCM=true,                                                                                                                                                                                                                                                              
#    STORE_EPIDEMIC_SCM=true                                                                                                                                                                                                                                                              
#    )

# con = run_simulations(                                                                                                                                                                                                                                                         
#    1,                                                                                                                                                                                                                                             
#    ReactiveAgentsDriver.network_parameters(30),                                                                                                                                                                                                                                               
#    10,                                                                                                                                                                                                                                                                                   
#    ReactiveAgentsDriver.behavior_parameters("Watts", "Watts", 5, 5),                                                                                                                                                                                                                          
#    1,                                                                                                                                                                                                                                                                                   
#    100,                                                                                                                                                                                                                                                                                  
#    con,                                                                                                                                                                                                                                                                                 
#    STORE_NETWORK_SCM=true,                                                                                                                                                                                                                                                              
#    STORE_EPIDEMIC_SCM=true                                                                                                                                                                                                                                                              
#    )

disconnect_from_database!(con)

